name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/hackaweather
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  TAG: pr-${{github.event.pull_request.number}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: askpt
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
          context: ./src/hackAWeather
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
    - name: Performance test
      run:  docker-compose run -e DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}  -T --rm load-test run --out statsd - <loadSpikeSoakScript.js
